%ifndef GRAPHICS_INC_
 %define GRAPHICS_INC_

 %include	"CSFML/Graphics/Font.inc"
 %include	"CSFML/Graphics/Image.inc"
 %include	"CSFML/Graphics/Rect.inc"
 %include	"CSFML/Graphics/Sprite.inc"
 %include	"CSFML/Graphics/Texture.inc"
 %include	"CSFML/Graphics/Transform.inc"
 %include	"CSFML/Graphics/VertexArray.inc"
 %include	"CSFML/Graphics/View.inc"
 %include	"CSFML/Graphics/Text.inc"

%endif ; GRAPHICS_INC_
