%ifndef SF_EVENT_INC_
 %define SF_EVENT_INC_

 %define sfEvtClosed			0
 %define sfEvtResized			1
 %define sfEvtLostFocus			2
 %define sfEvtGainedFocus		3
 %define sfEvtTextEntered		4
 %define sfEvtKeyPressed		5
 %define sfEvtKeyReleased		6
 %define sfEvtMouseWheelMoved		7
 %define sfEvtMouseButtonPressed	8
 %define sfEvtMouseButtonReleased	9
 %define sfEvtMouseMoved		10
 %define sfEvtMouseEntered		11
 %define sfEvtMouseLeft			12
 %define sfEvtJoystickButtonPressed	13
 %define sfEvtJoystickButtonReleased	14
 %define sfEvtJoystickMoved		15
 %define sfEvtJoystickConnected		16
 %define sfEvtJoystickDisconnected	17

%endif ; SF_EVENT_INC_