%ifndef SF_RENDER_WINDOW_INC_
 %define SF_RENDER_WINDOW_INC_

extern	 sfRenderWindow_create

extern	 sfRenderWindow_setFramerateLimit

extern	 sfRenderWindow_clear
extern	 sfRenderWindow_drawSprite
extern	 sfRenderWindow_drawText
extern	 sfRenderWindow_drawVertexArray
extern	 sfRenderWindow_display
extern	 sfRenderWindow_setView

extern	 sfRenderWindow_isOpen
extern	 sfRenderWindow_pollEvent
extern	 sfRenderWindow_close

extern	 sfRenderWindow_destroy

%endif ; SF_RENDER_WINDOW_INC_